name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=j(8h1fqzw*khgz&^93^^m^18xe3xn!s-x-h_4+^9d!ws5fn@md
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=k2PWbDj7oOUSbEXyXN7tLqWC
      - PASSAGE_API_KEY=Dv986HHdgc.HAeHvOpgLnTCVNTqBNixCanoo5WU4h6yYllmbxoIFMb8TvySwIXhdw3gaArCnoEN
    ports:
      - 8000:8000
